// ============================================
// SaaS Plan Definitions — single source of truth
// Framework-neutral (NO 'use client'): safe to import from both server API
// routes and client components. Previously these were duplicated in
// subscription.js, api/admin/onboarding, onboarding/page and the landing page,
// which could drift (esp. per-plan feature flags). Everything now imports here.
// ============================================

export const PLAN_DEFINITIONS = {
  trial: {
    id: 'trial',
    type: 'trial',
    name: { ar: 'تجريبية مجانية', en: 'Free Trial' },
    durationDays: 90,
    price: 0,
    currency: 'EGP',
    maxMembers: 100,
    maxTrainers: 3,
    features: {
      ai_nutrition: false,
      ai_workout: false,
      ai_churn: false,
      ai_sentiment: false,
      ai_pricing: false,
      ai_chatbot: false,
      ai_body_analysis: false,
      ai_social: false,
      advanced_analytics: true,
      spa_module: true,
      inventory_module: true,
      hr_module: true,
      sms_notifications: true,
    },
    order: 0,
  },
  monthly: {
    id: 'monthly',
    type: 'monthly',
    name: { ar: 'الخطة الشهرية', en: 'Monthly Plan' },
    durationDays: 30,
    price: 500,
    currency: 'EGP',
    maxMembers: 300,
    maxTrainers: 5,
    features: {
      ai_nutrition: true,
      ai_workout: true,
      ai_churn: true,
      ai_sentiment: true,
      ai_pricing: true,
      ai_chatbot: true,
      ai_body_analysis: true,
      ai_social: true,
      advanced_analytics: true,
      spa_module: true,
      inventory_module: true,
      hr_module: true,
      sms_notifications: true,
    },
    order: 1,
  },
  quarterly: {
    id: 'quarterly',
    type: 'quarterly',
    name: { ar: 'ربع سنوية', en: 'Quarterly Plan' },
    durationDays: 90,
    price: 1200,
    currency: 'EGP',
    discount: 20,
    maxMembers: 500,
    maxTrainers: 10,
    features: {
      ai_nutrition: true,
      ai_workout: true,
      ai_churn: true,
      ai_sentiment: true,
      ai_pricing: true,
      ai_chatbot: true,
      ai_body_analysis: true,
      ai_social: true,
      advanced_analytics: true,
      spa_module: true,
      inventory_module: true,
      hr_module: true,
      sms_notifications: true,
    },
    order: 2,
  },
  semi_annual: {
    id: 'semi_annual',
    type: 'semi_annual',
    name: { ar: 'نصف سنوية', en: 'Semi-Annual Plan' },
    durationDays: 180,
    price: 2100,
    currency: 'EGP',
    discount: 30,
    maxMembers: 1000,
    maxTrainers: 20,
    features: {
      ai_nutrition: true,
      ai_workout: true,
      ai_churn: true,
      ai_sentiment: true,
      ai_pricing: true,
      ai_chatbot: true,
      ai_body_analysis: true,
      ai_social: true,
      advanced_analytics: true,
      spa_module: true,
      inventory_module: true,
      hr_module: true,
      sms_notifications: true,
    },
    order: 3,
  },
  annual: {
    id: 'annual',
    type: 'annual',
    name: { ar: 'سنوية', en: 'Annual Plan' },
    durationDays: 365,
    price: 3600,
    currency: 'EGP',
    discount: 40,
    maxMembers: -1, // Unlimited
    maxTrainers: -1,
    features: {
      ai_nutrition: true,
      ai_workout: true,
      ai_churn: true,
      ai_sentiment: true,
      ai_pricing: true,
      ai_chatbot: true,
      ai_body_analysis: true,
      ai_social: true,
      advanced_analytics: true,
      spa_module: true,
      inventory_module: true,
      hr_module: true,
      sms_notifications: true,
    },
    order: 4,
  },
};

// ==================== AI Feature Keys ====================
export const AI_FEATURES = [
  'ai_nutrition',
  'ai_workout',
  'ai_churn',
  'ai_sentiment',
  'ai_pricing',
  'ai_chatbot',
  'ai_body_analysis',
  'ai_social',
];

export const AI_FEATURE_LABELS = {
  ai_nutrition: { ar: 'مساعد التغذية الذكية', en: 'AI Nutrition Assistant', icon: '🥗' },
  ai_workout: { ar: 'مولّد برامج التمارين', en: 'AI Workout Generator', icon: '🏋️' },
  ai_churn: { ar: 'التنبؤ بمغادرة الأعضاء', en: 'Churn Prediction', icon: '📊' },
  ai_sentiment: { ar: 'تحليل المشاعر', en: 'Sentiment Analysis', icon: '💬' },
  ai_pricing: { ar: 'التسعير الذكي', en: 'Smart Pricing', icon: '💰' },
  ai_chatbot: { ar: 'المساعد الذكي', en: 'AI Chatbot', icon: '🤖' },
  ai_body_analysis: { ar: 'تحليل صور الجسم', en: 'Body Analysis', icon: '📸' },
  ai_social: { ar: 'التوصيات الاجتماعية', en: 'Social Recommendations', icon: '👥' },
};
